[general]
copy-command = "wl-copy"
focus-toggles-toolbars = true
actions-on-right-click = ["save-to-clipboard"]
output-filename = "~/Pictures/Screenshot/%Y-%m-%d_%H%M%S.png"
early-exit = true
corner-roundness = 5

[font]
family = "Noto Sans SC"
style = "Regular"

fallback = [
    "Noto Sans CJK SC",  # 不知道有没有区别
    "Twemoji"
]
